services:
  emqx:
    image: emqx/emqx:latest
    hostname: emqx_broker
    ports:
      - "1883:1883"   # MQTT TCP port
      # - "8083:8083"   # MQTT WebSocket port
      # - "8084:8084"   # MQTT secure WebSocket port
      # - "8883:8883"   # MQTT SSL port
      - "18083:18083" # EMQX Dashboard port
    environment:
      # Set the dashboard admin password (default username is 'admin')
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "password"
      # Set the node name for clustering (optional, but recommended for persistence)
      EMQX_NODE__NAME: "emqx@emqx_broker" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/api/v5/status"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
      - ./emqx/provisioning/declarative/base.hocon:/opt/emqx/etc/base.hocon
      - ./emqx/provisioning/declarative/user.json:/opt/emqx/etc/user.json
    networks:
      - database-network
      - emqx-network
      
### Deprecated: Using base.hocon and volume mounts for configuration instead of API provisioning.
### Keeping this service definition for reference.
  # emqx-init:
  #   build:
  #     context: ./emqx 
  #   depends_on:
  #     emqx:
  #       condition: service_healthy
  #   networks:
  #     - emqx-network
  
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
      - database-network

  grafana:
    image: docker.io/grafana/grafana-oss:12.1.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - backend-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      grafana:
        condition: service_started
    networks:
      - backend-network
      - database-network

    
networks:
  database-network:
    driver: bridge
  backend-network:
    driver: bridge
  emqx-network:
    driver: bridge

volumes:
  grafana-data:
  mongo_data:
  emqx_data:
  emqx_log:
