actions {
  mongodb {
    store_events {
      connector = MongoDB
      enable = true
      parameters {
        collection = events
        payload_template = """{"clientid": "${clientid}", "topic": "${topic}", "qos": "${qos}", "id": "${payload.id}", "event": "${payload.event}", "result": "${payload.result}", "timestamp": "${payload.timestamp}"}"""
      }
    }
    store_metrics {
      connector = MongoDB
      enable = true
      parameters {
        collection = metrics
        payload_template = """{"clientid": "${clientid}", "topic": "${topic}", "qos": "${qos}", "id": "${payload.id}", "cpu": "${payload.cpu}", "temperature": "${payload.temperature}", "timestamp": "${payload.timestamp}"}"""
      }
    }
    store_status {
      connector = MongoDB
      enable = true
      parameters {
        collection = status
        payload_template = """{"clientid": "${clientid}", "topic": "${topic}", "qos": "${qos}", "id": "${payload.id}", "state": "${payload.state}", "last_unlock": "${payload.last_unlock}", "battery": "${payload.battery}", "error": "${payload.error}", "timestamp": "${payload.timestamp}"}"""
      }
    }
  }
}