rule_engine {
  ignore_sys_message = true
  jq_function_default_timeout = "10s"
  rules {
    "metrics_rule" {
      actions = [
        "mongodb:store_metrics"
      ]
      enable = true
      name = vault_metrics_rule
      sql = """~
        SELECT * FROM "vault/padlock/metrics"~"""
    }
    "event_rule" {
      actions = [
        "mongodb:store_events"
      ]
      enable = true
      name = vault_event_rule
      sql = """~
        SELECT * FROM "vault/padlock/event"~"""
    }
    "status_rule" {
      actions = [
        "mongodb:store_status"
      ]
      enable = true
      name = vault_status_rule
      sql = """~
        SELECT * FROM "vault/padlock/status"~"""
    }
  }
}